global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # API Gateway metrics
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Task Service metrics
  - job_name: 'task-service'
    static_configs:
      - targets: ['task-service:8001']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Import Service metrics
  - job_name: 'import-service'
    static_configs:
      - targets: ['import-service:8003']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Realtime Worker metrics
  - job_name: 'realtime-worker'
    static_configs:
      - targets: ['realtime-worker:8004']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Redis metrics
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']

  # PostgreSQL metrics
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
