name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: '1.8.3'

      - name: Install dependencies
        working-directory: backend
        run: |
          poetry env use 3.11
          poetry install

      - name: Run tests
        working-directory: backend
        run: |
          poetry run pytest -q

      - name: Lint (ruff)
        working-directory: backend
        run: |
          poetry run ruff check

      - name: Type check (mypy)
        working-directory: backend
        run: |
          poetry run mypy || true

      - name: Format check (black)
        working-directory: backend
        run: |
          poetry run black --check .

